export interface ArticleBlock {
  type: "h2" | "h3" | "p" | "quote" | "ul" | "ol";
  text?: string;
  items?: string[];
  author?: string;
}

export interface Article {
  slug: string;
  title: string;
  date: string;
  readTime: string;
  tag: string;
  desc: string;
  content: ArticleBlock[];
}

export const ARTICLES: Article[] = [
  {
    slug: "ai-for-small-business-automation",
    title: "AI for small business: how automation actually saves time",
    date: "May 1, 2026",
    readTime: "10 min read",
    tag: "AI Automation",
    desc: "Most small businesses claim they're 'using AI' when someone opened ChatGPT to draft a message. Genuine AI implementation transforms tangible workflows: reconciliation from five days to hours, commissions from days to minutes.",
    content: [
      { type: "p", text: "Most small businesses claim they are \"using AI\" when they actually mean someone on staff opened ChatGPT to draft a message. This differs fundamentally from automation. Genuine AI implementation for small business occurs when a tangible workflow transforms: month-end reconciliation shifts from four to five days down to a few hours, commissions move from taking two to three days to completing in minutes, or purchasing review drops from one to two days to fifteen minutes with human review retained." },
      { type: "p", text: "This represents the genuine opportunity: operating the business more cleanly rather than adding another software subscription." },
      { type: "h2", text: "What AI for Small Business Actually Means" },
      { type: "p", text: "For organizations with 20 to 250 employees, AI typically does not replace staff. Instead, it accelerates repetitive work already embedded in accounting, operations, purchasing, sales, and administration while improving consistency." },
      { type: "ul", items: ["The human transitions from line-by-line typing to reviewing anomalies.", "AI shifts from experimental tool to production system working against actual business information.", "The workflow strengthens progressively rather than being delivered once and shelved."] },
      { type: "quote", text: "It might not get it right at first. But as you get further along, it'll make less and less mistakes, to where it gets to a point where there's no mistakes made.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "The First Step Is Not the AI Tool" },
      { type: "p", text: "The first step involves the information itself. When sales presentations reside on ten separate devices, accounting references scatter across three folders, process documentation exists only in individual memory, and the team uses different versions of shared files, the language model cannot work with a coherent business. It encounters fragments instead." },
      { type: "quote", text: "When we get a client, the first thing we have to do is get all your data into one repository. So think of that data as a brain. That brain is what feeds the large language model.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "ul", items: ["Moving critical operational information into one central location.", "Removing redundant copies.", "Identifying which file represents the authoritative version.", "Establishing access restrictions based on role requirements."] },
      { type: "h2", text: "AI Governance Is Not Optional" },
      { type: "p", text: "The second misstep involves assuming that employee AI use already constitutes organizational AI strategy. Usually, the reverse holds true: an uncontrolled environment featuring personal accounts, free subscriptions, and no oversight of information movement." },
      { type: "quote", text: "The marketing team may be using ChatGPT, the accounting team may be using Claude or Gemini, and they might be using prosumer accounts, personal accounts that have different terms of service than what you might want for your business.", author: "Steven, Senior Engineer, Fornida" },
      { type: "p", text: "Two distinct risks emerge. First, external exposure: proprietary details, customer records, financial data, or private files uploaded into unapproved services. Second, internal exposure: even with approved platforms, inadequate permission structures allow improper access distribution." },
      { type: "h2", text: "What AI Automation Looks Like in the Real World" },
      { type: "h3", text: "1. Accounting Reconciliation" },
      { type: "p", text: "Fornida's accounting personnel were manually cross-referencing charge card statements, acquisition orders, revenue orders, and GL classifications at month conclusion. This proved tedious, repetitive, and susceptible to mistakes." },
      { type: "quote", text: "Before, they would get the credit card statement, all our sales orders, all our purchase orders, and they would be reconciling at the end of the month. It would take them about a week, if not four to five days.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "quote", text: "Instead of him having to go manually review all, let's say, 800 transactions in these credit card statements, the AI flags the ones that it has not identified yet. So it could be as little as 30 transactions versus the 800 transactions that he's going through.", author: "Steven, Senior Engineer, Fornida" },
      { type: "h3", text: "2. Commission Reports" },
      { type: "quote", text: "Our team used to take two, three days to run commissions. Now it's done in minutes.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h3", text: "3. Purchasing and Inventory Review" },
      { type: "p", text: "Fornida's internal sourcing method illuminates situations where human involvement remains essential. Previously, personnel manually examined stock levels, assessed consumption trends, and formulated buying plans from initial concepts. This consumed one or two days. Following automation, this phase compressed to roughly fifteen minutes with red/orange/green decision guidance." },
      { type: "h2", text: "What to Automate First" },
      { type: "p", text: "Superior initial automation typically demonstrates four characteristics:" },
      { type: "ul", items: ["It recurs consistently.", "It adheres to recognizable structures.", "It currently demands measurable staff attention monthly or weekly.", "Problems remain noticeable and addressable."] },
      { type: "h2", text: "What the First 30 Days Should Look Like" },
      { type: "h3", text: "Week 1: Usage and Data Audit" },
      { type: "p", text: "Assess what employees presently leverage, what information exists in unified form, what remains scattered, and where obvious access constraints exist." },
      { type: "h3", text: "Week 2: Clean the Company Brain" },
      { type: "p", text: "Recognize the primary storage system, resolve document multiplication, establish the authentic reference, and implement role-dependent access management." },
      { type: "h3", text: "Week 3: Choose One Workflow" },
      { type: "p", text: "Choose the unglamorous function demonstrating quantifiable disruption. This typically involves accounting, commissions, reporting, estimation, or comparable recurring administrative functions." },
      { type: "h3", text: "Week 4: Ship Version One with a Human in the Loop" },
      { type: "p", text: "Avoid demanding flawlessness from inception. Implement an operational preliminary release, enable the operator to assess results, and progressively decrease error frequency." },
      { type: "h2", text: "Start With One Workflow That Already Hurts" },
      { type: "p", text: "When your organization currently loses days monthly to reconciliation, commissions, estimation, reporting, or comparable repetitive activity, this frequently represents the optimal starting point. Not because of prestige. Because it proves apparent. The temporal loss is genuine, the achievement is demonstrable, and people embrace transformation when difficulty is evident." },
    ],
  },
  {
    slug: "ai-training-for-employees",
    title: "AI training for employees: teach your team to build, not just chat",
    date: "Apr 23, 2026",
    readTime: "11 min read",
    tag: "AI Strategy",
    desc: "Real AI training isn't about better prompts. It's about teaching staff to build the small workflows they used to wait on. The four-hour rule, the people closest to the work, and why it has to be ongoing.",
    content: [
      { type: "p", text: "Most AI training for employees is built around the wrong question. It asks how to make a marketing person better at writing prompts, or how to teach an account manager to summarize a meeting. That is not training. That is chatbot literacy. The actual question is whether the people closest to the work — the warehouse picker, the bookkeeper, the inside sales rep — can build the workflow they want instead of waiting on a programmer or a consultant." },
      { type: "p", text: "That is where Fornida draws the line. If a workflow takes someone in your company less than four hours to build with the right tools, the company should learn to build it. Not hire it out. Not put it in a backlog. Build it." },
      { type: "h2", text: "The 60-Second Version" },
      { type: "ul", items: ["Real AI training for employees is not about better prompts. It is about teaching staff to build the small workflows they used to wait on.", "The four-hour rule: if a workflow takes under four hours to build, your team should learn to do it themselves. Anything over four hours becomes a statement of work.", "The people who understand the work best — warehouse, accounting, sales — are the ones who should be building the automations.", "Governance comes first. Approved tools, the right licenses, no trade secrets going into free chat windows.", "The training is ongoing, not a workshop. Tools change every few weeks."] },
      { type: "h2", text: "What 'AI Training' Usually Means and Why It Falls Short" },
      { type: "quote", text: "If your team is just using it for emails, you're falling way behind. You should be using it for things like reconciliation at the end of the month.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "The Four-Hour Rule" },
      { type: "p", text: "Fornida's AI Advantage service is built on a simple operating rule. Under four hours of work is bundled into the monthly fee — the client team learns how to do it, or Fornida helps them across the line. Over four hours, it becomes a statement of work." },
      { type: "quote", text: "Whatever can be done under four hours, we'll just go ahead and do. If it's over four hours, we give you a statement of work. We're so used to doing this stuff and we use the AI to do it that it usually goes pretty quickly.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "Teach, Do Not Do" },
      { type: "quote", text: "We realized we could teach our clients how to do this. They can essentially learn how to fish, instead of us fishing for them and charging them exorbitant amounts of money.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "The People Who Should Be Building Are Not in IT" },
      { type: "quote", text: "The people inside of your business that understand your business the best are gonna be the ones that should be building whatever automation you need. They understand it better than anyone.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "p", text: "The proof is sitting inside Fornida's own operations. Three workflows ran on the same playbook:" },
      { type: "ul", items: ["Accounting reconciliation — used to eat four or five days every month — dropped to a few hours.", "Commission reports — used to take two or three days — dropped to minutes.", "Purchasing review — used to take a day or two — dropped to about fifteen minutes with red, orange, and green flags for the human to make the final call."] },
      { type: "h2", text: "What Employees Actually Need to Learn" },
      { type: "h3", text: "A Clean Place for the Data to Live" },
      { type: "p", text: "If the company's information is scattered across personal hard drives, three SharePoint folders, and a couple of Dropbox accounts, no amount of employee training will produce a useful workflow. The model needs a single repository to work against." },
      { type: "h3", text: "Approved Tools and the Right Licenses" },
      { type: "quote", text: "If they're using just an individual license or a free license, all the information they're inputting into that large language model is considered free information. If you end up in court, all that information is no longer attorney-client privilege. It's no longer a trade secret either.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h3", text: "A Way to Ask Questions Without Slowing Down" },
      { type: "quote", text: "If I can do it, anybody can do it. But I asked a thousand questions from our team in order to get to that step.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "Why It Has to Be Ongoing, Not a Workshop" },
      { type: "quote", text: "These models are starting to outdo each other. You don't know which model you're gonna be using in perpetuity. So you need somebody like an MSP, where you could just pick up the phone and call that help desk.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "What a Real First Quarter Looks Like" },
      { type: "ol", items: ["Get the data into one place. Single source of truth, permissions in order, duplicates removed.", "Lock down approved tools, licenses, and access. No personal accounts, no free tiers, no surprise data leakage.", "Pick one workflow that already hurts. Accounting, commissions, purchasing, quoting, reporting, scheduling.", "Train the operator who runs that workflow today, with a partner on call for the questions they cannot answer alone.", "Ship a first version inside four hours where possible. Tune from there.", "When the first workflow works, the operator notices the next one. Repeat."] },
    ],
  },
  {
    slug: "ai-governance-for-small-business",
    title: "AI Governance for Small Business: Approved Tools Before Automation",
    date: "Apr 16, 2026",
    readTime: "6 min read",
    tag: "AI Strategy",
    desc: "If your employees are already using ChatGPT, Claude, Gemini, or Copilot on their work machines, that does not mean your company has an AI strategy. It usually means the opposite.",
    content: [
      { type: "p", text: "If your employees are already using ChatGPT, Claude, Gemini, or Copilot on their work machines, that does not mean your company has an AI strategy. It usually means the opposite. It means employees found useful tools faster than leadership built rules for them." },
      { type: "p", text: "That is the real starting point for AI governance for small business. Before you automate workflows or buy more licenses, you need to answer four basic questions:" },
      { type: "ul", items: ["Which tools are approved?", "Which license tiers are approved?", "What business data can those tools touch?", "Who can see what once AI is in the loop?"] },
      { type: "h2", text: "The Problem Is Not That Employees Use AI" },
      { type: "p", text: "The problem is that they are probably using it in different ways, with different accounts, under different terms. Marketing may be using one model, accounting may be using another, and both teams may be using prosumer or personal accounts that have terms of service the business never reviewed. That means leadership does not really know what data is being uploaded, where it is going, whether the licensing is appropriate, or whether confidential material is being exposed." },
      { type: "h2", text: "What Good AI Governance for a Small Business Actually Covers" },
      { type: "h3", text: "1. Approved Tools" },
      { type: "p", text: "The company needs to decide which models or AI products are acceptable for work use. That sounds obvious, but many SMBs skip it. Employees default to whatever tool they already know. Approving tools does not mean one model must do everything. It means the company should not let every employee choose their own platform with no oversight." },
      { type: "h3", text: "2. Approved License Tiers" },
      { type: "p", text: "A tool might be acceptable in principle, but the wrong license tier can create data-handling problems, logging gaps, or terms-of-service issues the business never intended to accept. Owners often do not realize what changes when employees use free or individual licenses instead of approved business licensing." },
      { type: "h3", text: "3. Visibility and Enforcement" },
      { type: "p", text: "You need to know whether employees are actually using the approved tools and whether they are bypassing them. Otherwise the policy is just a suggestion." },
      { type: "h3", text: "4. Access Control" },
      { type: "p", text: "Even the right model becomes risky if it can see the wrong data. Small businesses do not get a pass here. Finance data is still finance data. HR data is still HR data. Giving an AI-enabled workflow broad access because it is convenient is the same mistake as giving a user broad access because it is convenient." },
      { type: "h2", text: "Why 'Everyone Is Already Using ChatGPT' Is the Wrong Comfort Signal" },
      { type: "p", text: "Owners sometimes take employee AI adoption as proof the company is ahead. It usually proves only that the employees found utility before the company built discipline. That is why AI governance should be set before automation scales. It is much easier to approve a few tools and shape user behavior early than to unwind bad habits after six months of unmanaged usage." },
      { type: "h2", text: "The SMB Version Should Be Simpler, Not Looser" },
      { type: "p", text: "A lot of enterprise AI governance material is bloated. Most SMBs need:" },
      { type: "ul", items: ["One approved-tool list", "One basic usage policy", "One access-control model", "One way to monitor compliance"] },
      { type: "h2", text: "Governance Before Scale" },
      { type: "p", text: "If your company is still early in AI adoption, this is the right order:" },
      { type: "ol", items: ["Centralize and clean the important data.", "Approve the tools and license tiers.", "Set permissions and visibility.", "Start with one workflow worth automating."] },
      { type: "h2", text: "The Goal Is Not to Slow the Team Down" },
      { type: "p", text: "Good AI governance for small business should not feel like a bureaucratic brake on useful work. It should feel like guardrails: the right tools, the right access, the right data, the right visibility. That makes the useful workflows easier to approve and easier to repeat. If your employees are already using AI, do not treat that as the finish line. Treat it as a signal that governance needs to catch up before automation expands further." },
    ],
  },
  {
    slug: "data-cleanup-before-ai",
    title: "Data Cleanup Before AI: Why Your Agentic Rollout Fails on Messy Data",
    date: "Apr 9, 2026",
    readTime: "6 min read",
    tag: "AI Automation",
    desc: "Most small businesses want the AI tool first. The actual first step is much less exciting: data cleanup. The model is only as useful as the operating environment it can see.",
    content: [
      { type: "p", text: "Most small businesses want the AI tool first. The actual first step is much less exciting: data cleanup. If the important files in your company are scattered across employee laptops, buried in duplicate folders, and split across six versions of the same sales deck, a language model will not fix that mess. It will read from it. Then it will give you output shaped by whatever it found first." },
      { type: "h2", text: "What Messy Data Actually Looks Like in a Small Business" },
      { type: "p", text: "Messy data is rarely one dramatic problem. It is usually a hundred small ones:" },
      { type: "ul", items: ["Ten versions of the same sales deck", "Pricing sheets saved on three different laptops", "Process notes living in somebody's inbox", "Accounting references stored in exports nobody else can find", "SharePoint partially used, but not trusted"] },
      { type: "p", text: "Farzad Vahid's explanation is the simple version: before you automate anything, you have to get the company's information into one repository and make sure that repository contains the right data. The model needs a brain to work against. Without it, you are giving AI fragments rather than context." },
      { type: "h2", text: "Why Agentic AI Rollouts Fail on Dirty Inputs" },
      { type: "p", text: "When an owner says 'we turned on the AI tool and it was not that useful,' the problem is rarely the tool. It is the underlying data environment. If your model can see duplicate files, outdated references, inconsistent naming, and unclear permissions — the output will feel inconsistent too. This is a source-of-truth problem before it is a hallucination problem." },
      { type: "h2", text: "The 'Ten Sales Decks' Problem" },
      { type: "p", text: "You have ten different sales decks. One is from last quarter. One is from a salesperson's desktop. One got revised for a prospect and saved as a different file. One is in SharePoint but nobody trusts that it is the latest one. Then the business turns on AI and expects the model to 'know' which one matters. It does not know. It reads what is available." },
      { type: "ul", items: ["Decide which file is the approved one.", "Remove or archive the duplicates.", "Put the approved version in the right repository.", "Set permissions around who can edit or view it."] },
      { type: "h2", text: "What Data Cleanup Before AI Usually Involves" },
      { type: "h3", text: "1. Find the Important Operating Data" },
      { type: "p", text: "This is not every file in the company. It is the data that the workflows depend on: sales collateral, pricing references, accounting references, process documentation, HR or operational forms. The goal is not perfection. The goal is to identify what the business actually uses to make decisions." },
      { type: "h3", text: "2. Pick the Repository That Becomes the Source of Truth" },
      { type: "p", text: "One repository, one approved structure, one place the model can look. The specific tool matters less than the rule." },
      { type: "h3", text: "3. Dedupe and Kill Version Sprawl" },
      { type: "p", text: "This is the part teams resist because it feels tedious. It is also where the real quality gain happens. If you leave the old copies sitting beside the new ones, the mess is still there. The model cannot distinguish 'legacy file nobody should use' from 'current file leadership approved.'" },
      { type: "h3", text: "4. Set Permissions Before the Rollout" },
      { type: "p", text: "Not everybody should see finance. Not everybody should see HR. Not every AI-enabled workflow should inherit broad access just because a folder exists. Data cleanup without access control is not enough." },
      { type: "h2", text: "Signs Your Business Needs Data Cleanup Before AI" },
      { type: "ul", items: ["Employees keep asking which file is the latest one.", "Teams save important material locally because they do not trust the shared repository.", "Different departments use different versions of the same document.", "Search inside your repository returns too many conflicting answers.", "Leadership thinks AI is underperforming, but nobody has audited the data it can see."] },
      { type: "h2", text: "Clean the Environment Before You Blame the Model" },
      { type: "p", text: "Most SMB AI rollouts do not fail because the model is bad. They fail because the business expected the model to compensate for scattered files, conflicting versions, and undefined permissions. Clean up the data first. Build the company brain. Then the workflow has something reliable to read from, and the model has a real chance to be useful." },
    ],
  },
  {
    slug: "workflow-automation-for-small-business",
    title: "Workflow Automation for Small Business: Start With the Spreadsheet Nobody Wants",
    date: "Apr 2, 2026",
    readTime: "7 min read",
    tag: "AI Automation",
    desc: "Most owners picture something ambitious when they hear workflow automation. The right first workflow is usually boring — the spreadsheet nobody wants to touch, the report that takes two days every month.",
    content: [
      { type: "p", text: "Most owners hear 'workflow automation for small business' and picture something ambitious: an AI assistant for the whole company, a chatbot that answers everything, maybe a giant systems project that changes everything at once. That is usually the wrong first move." },
      { type: "p", text: "The right first workflow is usually boring. It is the spreadsheet nobody wants to touch, the report that takes two days every month, or the repetitive review process that depends on one employee typing line by line into a system. Those are the automations that ship fastest, get adopted fastest, and produce a before-and-after a small business can actually feel." },
      { type: "h2", text: "Start With the Workflow That Already Hurts" },
      { type: "p", text: "The best first automation candidate usually has four traits:" },
      { type: "ul", items: ["It is repetitive.", "It follows recognizable patterns.", "It already eats real employee time every week or every month.", "When mistakes happen, they are visible and fixable."] },
      { type: "h2", text: "Why Boring Workflows Win First" },
      { type: "p", text: "Owners often want the first automation project to prove the entire AI strategy. That instinct usually produces a messy project because the workflow is too broad, too undefined, or too dependent on scattered data. The boring workflows win first because they already have a shape: a clear input, a repeatable set of steps, a known output, and a visible pain point." },
      { type: "h2", text: "Three Workflow Types That Are Usually Worth Automating" },
      { type: "h3", text: "1. Finance and Accounting Workflows" },
      { type: "p", text: "These are strong candidates because the work is repetitive, rules-shaped, and costly when errors compound." },
      { type: "ul", items: ["Credit-card reconciliation", "GL bucketing", "Expense classification", "Commission calculations"] },
      { type: "h3", text: "2. Operations and Purchasing Workflows" },
      { type: "p", text: "These are good candidates when a team is already working from exports, spreadsheets, run-rate history, or inventory snapshots. The point is not to let AI 'run purchasing.' The point is to shorten a manual review cycle that currently consumes a day or two of human attention." },
      { type: "h3", text: "3. Sales-Support Workflows" },
      { type: "p", text: "This is where quoting, BOM generation, call summarization, and commission reporting start to become interesting. A hardware-side quoting workflow where a request involving multiple server builds could take hours to put together manually — using an AI-assisted agent, the same output in about fifteen minutes." },
      { type: "h2", text: "What Not to Automate First" },
      { type: "p", text: "A bad first workflow usually looks like one of these:" },
      { type: "ul", items: ["\"Build an AI assistant for the whole company.\"", "\"Make AI answer every employee question.\"", "\"Automate this process we have never documented.\"", "\"Turn on Copilot and see what happens.\""] },
      { type: "h2", text: "The First Version Does Not Have to Be Perfect" },
      { type: "p", text: "One of the biggest misunderstandings in workflow automation for small business is the expectation that the first version should be final. Fornida's internal pattern has been consistent:" },
      { type: "ol", items: ["Ship the first workable version.", "Watch where it misses.", "Correct the mapping, rules, or prompts.", "Shrink the exception count over time."] },
      { type: "p", text: "That is how the accounting workflow got better. That is how commission reporting became trustworthy enough that the team stopped arguing with the output. The workflow is not a static deliverable. It is a tuned operating system for one piece of the business." },
      { type: "h2", text: "What a Good First Win Looks Like" },
      { type: "ul", items: ["\"This task used to take two days. Now it takes twenty minutes.\"", "\"This person used to type every line. Now they review exceptions.\"", "\"This report used to trigger spreadsheet fights. Now the team trusts the output.\"", "\"This process used to depend on one person holding everything in their head. Now it is documented and repeatable.\""] },
      { type: "h2", text: "Start With One Workflow, Not Five Tools" },
      { type: "p", text: "If you are evaluating workflow automation for small business, do not start by asking which AI tool everybody should buy. Start by asking which workflow already wastes the most human time in the most obvious way. That is usually where the money is. It is also where adoption comes easiest, because the people doing the work already want the pain to go away." },
    ],
  },
  {
    slug: "how-to-choose-your-first-ai-workflow",
    title: "How to Choose Your First AI Workflow",
    date: "Mar 24, 2026",
    readTime: "6 min read",
    tag: "AI Automation",
    desc: "Most small businesses ask the AI question in the wrong order. They ask which tool to buy. The better question is narrower: which workflow should go first?",
    content: [
      { type: "p", text: "Most small businesses ask the AI question in the wrong order. They ask which tool they should buy, which model they should standardize on, or whether they need an AI assistant for the whole company. The better question is narrower: which workflow should go first?" },
      { type: "p", text: "The right first AI workflow is usually repetitive, high-volume, and easy to verify. It already wastes obvious time. It already frustrates the person doing it. And it has a visible before-and-after when the workflow gets better." },
      { type: "h2", text: "The Four Traits of a Good First Workflow" },
      { type: "h3", text: "1. Repetitive" },
      { type: "p", text: "The process happens often enough that patterns exist." },
      { type: "ul", items: ["Monthly reconciliation", "Weekly reporting", "Recurring commissions", "Repetitive quoting or BOM generation"] },
      { type: "h3", text: "2. High Volume" },
      { type: "p", text: "The workflow needs enough inputs that a human is currently doing too much manual review, classification, sorting, or transformation. This is why accounting works so well. Hundreds of transactions create enough repetition that the workflow can learn useful structure." },
      { type: "h3", text: "3. Visible Pain" },
      { type: "p", text: "If nobody feels the pain, adoption will be weak. The best first workflow is the one where the operator says 'Yes, please fix this.' If the workflow only sounds important from the owner's point of view, it may not be the right first win." },
      { type: "h3", text: "4. Easy Verification" },
      { type: "p", text: "The human should be able to look at the output and tell whether it is useful. The easier it is to review, the easier it is to tune." },
      { type: "h2", text: "A Simple Scorecard for Choosing the First Workflow" },
      { type: "p", text: "Score candidate workflows from 1 to 5 on these questions:" },
      { type: "ol", items: ["How often does this happen?", "How much manual entry or repetitive review does it involve?", "How obvious is the time loss today?", "How easy would it be for a human to check the output?", "How clean is the underlying data?"] },
      { type: "p", text: "The workflows with the highest combined scores should go first." },
      { type: "h2", text: "Good First Workflows vs Bad First Workflows" },
      { type: "h3", text: "Usually Good First Workflows" },
      { type: "ul", items: ["Reconciliation", "Commissions", "Purchasing review", "Quoting support", "Recurring exports and transformations"] },
      { type: "h3", text: "Usually Bad First Workflows" },
      { type: "ul", items: ["'Build an AI assistant for everything'", "Undocumented internal processes", "Workflows that depend on highly political judgment", "Broad strategy work with no clean input structure"] },
      { type: "h2", text: "Do Not Pick the Workflow Just Because It Sounds Impressive" },
      { type: "p", text: "The better move is to choose the workflow that lets the business prove the operating model: AI handles the repetitive work, the human reviews the output, the workflow gets better over time, and the time savings are measurable. Once the team sees that happen once, the second automation becomes easier to identify and easier to trust." },
      { type: "h2", text: "Why Human-in-the-Loop Is Usually Right for the First Workflow" },
      { type: "p", text: "For a small business, the first automation usually should not remove human review completely. It should narrow the human workload. The point is to eliminate the part of the process that should never have needed that much human time in the first place. Judgment stays with the human." },
      { type: "h2", text: "The First Workflow Is Supposed to Teach the Business How to Think" },
      { type: "p", text: "After one good automation, people begin to notice other repetitive review cycles, other spreadsheet-heavy processes, other classification tasks that should not be manual. That is how an automation program compounds: from one workflow teaching the business where the next bottleneck lives, not from one giant deployment." },
      { type: "h2", text: "Pick the Clearest Pain, Not the Fanciest Idea" },
      { type: "p", text: "If you are trying to figure out how to use AI for small business, do not start with 'what can AI do?' Start with 'what workflow already wastes the most time in the most repeatable way?' That question usually leads to a better first project, a faster first win, and a much clearer path to the second workflow after it." },
    ],
  },
  {
    slug: "commission-automation-for-small-business",
    title: "Commission automation for small business: when the math stops being the argument",
    date: "Mar 17, 2026",
    readTime: "5 min read",
    tag: "AI Automation",
    desc: "Fornida previously spent two or three days per cycle running commissions. After workflow rebuilding, the process takes minutes — and the disputes that used to dominate the sales floor disappeared.",
    content: [
      { type: "h2", text: "The Problem: Manual Commissions Create Hidden Costs" },
      { type: "p", text: "Fornida previously spent two or three days per cycle running commissions. Numbers would be extracted from Microsoft Business Central, reshaped in spreadsheets, cross-checked manually, then sent to the sales team. Disputes would arise, requiring recalculation and delays. After workflow rebuilding, the process takes minutes — reps review statements and either approve or flag specific lines." },
      { type: "p", text: "The core issue was not speed alone, but the deeper problem it masked: fragile math breeds organizational friction. When commission calculations require multiple days of manual effort, inconsistencies inevitably emerge. Rules get applied differently depending on who is processing them. New product lines accidentally inherit old calculation methods." },
      { type: "quote", text: "Our team used to take two, three days to run commissions. Now it's done in minutes...there's really no issues at this point because we've already debugged all that.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "After Automation: Arguments Shift to Policy, Not Calculation" },
      { type: "p", text: "Once automated, the math runs identically every cycle. Rules are documented. Calculations become reviewable. Reps disputing their numbers no longer question the arithmetic — the calculation is objective and traceable. What remains to discuss is policy itself." },
      { type: "p", text: "'I believe this account should pay the managed-services rate, not the hardware rate' is a substantive conversation leadership can address and implement consistently. By contrast, 'I think someone forgot to include my October deals' wastes time and erodes trust." },
      { type: "h2", text: "Why Spreadsheets Persist in Small Businesses" },
      { type: "p", text: "Most small and mid-sized businesses maintain commission spreadsheets not from preference, but because rules change frequently. Adding managed services to a hardware-focused model meant different commission structures. Automated systems hard-coded for the original comp plan break under these changes. Spreadsheets survive because they are editable by the team without tickets or external help. They are not ideal — they are flexible." },
      { type: "h2", text: "What Good Commission Automation Looks Like" },
      { type: "p", text: "Effective small-business commission automation is not a perfect black box. It is a reviewable workflow that delivers answers quickly with visible, manageable rules. Fornida's internal framework includes:" },
      { type: "ul", items: ["Rules in an editable location — leadership can modify them, not buried in code", "Consistent cycle execution — identical process every cycle against the same rules", "Visible calculations — reps see the math behind their total, not just the final number", "Flagged exceptions — human review catches edge cases", "Clean policy updates — comp plan changes apply next cycle without system rebuilds"] },
      { type: "h2", text: "The Broader Pattern" },
      { type: "p", text: "Commissions exemplify a wider principle applicable to any workflow where calculation creates friction: reconciliation, bonus payouts, pricing approvals. The underlying problem is typically the same: fragile, difficult-to-verify math. Automation does not eliminate policy debates. It disentangles them from arithmetic problems." },
      { type: "p", text: "For teams still spending days on commissions, the path mirrors Fornida's own approach: clean up inputs, document rules explicitly, run them consistently each cycle, and let human review be review — not reconstruction." },
    ],
  },
  {
    slug: "purchasing-automation-for-small-business",
    title: "Purchasing automation for small business: red, orange, green decision support",
    date: "Mar 11, 2026",
    readTime: "5 min read",
    tag: "AI Automation",
    desc: "Fornida's internal purchasing review was streamlined from one or two days to approximately 15 minutes. The system maintains human judgment while compressing the administrative burden.",
    content: [
      { type: "h2", text: "The Workflow Transformation" },
      { type: "p", text: "Fornida's internal purchasing review was streamlined from one or two days to approximately 15 minutes. The process previously required manual sorting work — pulling inventory, checking spreadsheets, analyzing run rates, and weighing profitability. The redesigned system maintains human judgment while compressing the administrative burden." },
      { type: "h2", text: "The Red, Orange, Green Pattern" },
      { type: "p", text: "Each purchase candidate receives one of three signals:" },
      { type: "ul", items: ["Green indicates immediate purchase. High-demand items with clear return on investment and no ambiguity.", "Orange signals uncertainty. Mixed data points requiring human review.", "Red recommends rejection. The financial case does not justify expenditure."] },
      { type: "p", text: "The color system concentrates human attention on what matters most. Greens bypass extended review. Reds get eliminated quickly. The orange items — those requiring genuine business judgment — receive focused analysis." },
      { type: "quote", text: "It spits out an answer. They still have to look at it and still make a judgment call. But it gives them red, you don't need to buy this. Orange, you might want to. Green, you have to buy these, this is a no-brainer.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "Why Purchasing Resists Full Automation" },
      { type: "p", text: "Complete automation carries asymmetric risks in purchasing:" },
      { type: "ul", items: ["Poor orders consume capital needed elsewhere", "Bad decisions damage vendor relationships built over years", "Excess inventory becomes financial liability", "The system becomes a vector for fraud and policy violations"] },
      { type: "p", text: "A fully automated system must be correct every time with no recovery options. A system providing sorted lists with color flags only requires accuracy on obvious decisions. Ambiguous cases remain human decisions." },
      { type: "h2", text: "How Human Work Reshapes" },
      { type: "h3", text: "Before Automation" },
      { type: "ul", items: ["Pull inventory", "Cross-check against historical run rates", "Sort by margin and velocity", "Decide what to order", "Cut the order"] },
      { type: "h3", text: "After Automation" },
      { type: "ul", items: ["Open the flagged list", "Skim greens, approve", "Look at oranges, decide", "Skip reds", "Cut the order"] },
      { type: "p", text: "Administrative grind disappears. Judgment remains. The reclaimed time creates capacity for identifying additional automation opportunities." },
      { type: "quote", text: "Each automation gives the team capacity to find the next one. Purchasing freed up enough time that we started pulling at other workflows we had been ignoring.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "Success Requirements" },
      { type: "ul", items: ["Unified data source. Purchasing data must be accessible and consistent. Fragmented spreadsheets and multiple locations undermine the system.", "Iterative refinement. Initial color thresholds, ROI rules, and run-rate windows require tuning. Performance improves between week one and week six.", "Infrastructure governance. The workflow needs approved tools, role-based access, and visibility into system inputs and logic."] },
    ],
  },
  {
    slug: "4am-data-exfil-supply-chain-edr-soc",
    title: "The 4 a.m. Download That Wasn't Supposed to Look Wrong",
    date: "Feb 26, 2026",
    readTime: "6 min read",
    tag: "Cybersecurity",
    desc: "A hardware manufacturer got hacked. The threat actors took device credentials. Weeks later, those credentials walked into a client's network looking exactly right — until 4 a.m., when the SOC noticed the size of the download.",
    content: [
      { type: "p", text: "A while back, a hardware manufacturer got hacked. The threat actors took device credentials with them. A few weeks later, those same credentials walked into one of our clients' networks, looking exactly the way they were supposed to look. The login was legitimate. The session was legitimate. The download was the size of a problem. At 4:00 a.m., on a normal-business network, somebody was pulling a tremendous amount of data out, and every authentication check in the stack was waving them through." },
      { type: "p", text: "This is the story of what almost happened, and the small thing that stopped it." },
      { type: "h2", text: "The 60-Second Version" },
      { type: "ul", items: ["What the attacker had: Real, valid credentials, stolen from an upstream hardware manufacturer that had been breached. Every login check passed.", "What gave them away: The timing. SentinelOne's EDR flagged the anomaly: a large download running at 4 a.m. on a network that doesn't normally move data at 4 a.m.", "Who made the call: The 24/7 SOC analyst, looking at the alert in real time.", "The decision: The SOC called our NOC. The NOC confirmed. We shut it down.", "The counterfactual: Without the SOC reading the behavior, the client would likely have been encrypted, ransomed, and possibly had data deleted. Catastrophic."] },
      { type: "h2", text: "The Detection" },
      { type: "p", text: "The credentials were correct. The user account was a real user. The endpoint was a real endpoint. None of the rules-based tooling had any reason to flag the session. From the perspective of identity and access, this was a normal Tuesday at 4 a.m. What SentinelOne flagged wasn't the who. It was the when and the how much." },
      { type: "quote", text: "There was a manufacturer that recently had an issue where they were hacked. In this instance, it looked like everything was performing correctly in this client's environment. The download that was happening had all the right credentials. SentinelOne didn't just flag it. It said, hey, why is this being downloaded this particular time?", author: "Farzad Vahid, CEO, Fornida" },
      { type: "quote", text: "The SOC called us, called our NOC, and said, hey, look, even though all the credentials are there, there's a tremendous amount of data being downloaded at 4:00 AM. This doesn't seem right.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "h2", text: "How We Got There" },
      { type: "quote", text: "We looked at it and said, this is not right. Shut it down. So we shut it down. We went and did some digging and found out that yes, a threat actor was downloading information, but they had the right credentials, because the manufacturer had a leak. They were actually hacked.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "p", text: "The credentials weren't compromised at the client. They were compromised upstream. A hardware manufacturer the client did business with had been breached, and credentials tied to that vendor's products had been carried into other environments. The client did nothing wrong. Their MFA was in place. Their patching was current. Their endpoints were managed. And the attacker walked through the front door anyway, because the keys were taken from somebody else." },
      { type: "h2", text: "Why Behavioral Detection Mattered" },
      { type: "p", text: "When the threat actor's session is authentic — real credentials, real account, real device — the only signal left is behavior. Behavioral detection asks the second question: is this normal? And it is only useful if a human is on the other end of the alert, awake at 4 a.m., willing to make the judgment call that 'this doesn't seem right' is enough to act on." },
      { type: "quote", text: "If this SOC wasn't in place, our client could have, I mean, they would have been encrypted, probably had ransom, may have had data deleted. It could have been catastrophic. But because of this SOC, it saved them.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "h2", text: "What This Means for Any Business" },
      { type: "ul", items: ["Your supply chain is your perimeter. Every vendor whose product touches your network is a credential surface you don't fully control. When a manufacturer gets breached, their product's credentials become your problem.", "Behavioral detection is not optional anymore. Rules-based tools catch attacks that match known patterns. The attacks that matter now match the shape of legitimate activity. Behavioral analysis is what catches the difference.", "The SOC is people. A 24/7 SOC is humans monitoring your network, making judgment calls about anomalies a tool surfaces. The tool flagged the timing. The analyst decided the timing mattered."] },
    ],
  },
  {
    slug: "financial-firm-no-mfa-wire-fraud-gap",
    title: "A financial firm wiring hundreds of millions a year had no MFA — what we found, what we deployed",
    date: "Feb 19, 2026",
    readTime: "5 min read",
    tag: "Cybersecurity",
    desc: "The most gaping security gap we'd ever walked into: a financial firm moving hundreds of millions in wire transfers every year with zero MFA on the systems controlling those wires.",
    content: [
      { type: "p", text: "It was the most gaping security gap we'd ever walked into. A financial services firm moving hundreds of millions of dollars in wire transfers every year had no MFA on the systems controlling those wires. No email security. No SOC. No EDR. Nothing had happened yet, and that was the only thing protecting them." },
      { type: "h2", text: "The 60-Second Version" },
      { type: "ul", items: ["Client: A financial services firm running hundreds of millions of dollars a year in wire transfers.", "What we found: Zero MFA on the wire-initiation systems. No email security. No SOC. No EDR.", "The risk: Wires are irreversible. Once one goes, there is no chargeback, no clawback, no civil recovery that gets the money back.", "What we deployed: MFA across the wire stack (Microsoft Authenticator and Duo by Cisco), behavioral email security (Avanan/Checkpoint), SentinelOne EDR with 24/7 SOC monitoring.", "The outcome: No incident has occurred since the rollout. The gap is closed."] },
      { type: "h2", text: "The Gap" },
      { type: "quote", text: "We've got a financial company that we work with, and they send a ton of wires, 'cause it's a financial firm. They do hundreds of millions of dollars in transactions a year. For us, it was unbelievable that they were doing a lot of these transactions and they didn't have any type of multifactor in place.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "quote", text: "If the credentials were ever given away, if somebody got 'em on a phishing email and got those credentials, there is no other backup. They didn't have that in place at all.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "h2", text: "Why Irreversibility Changes the Math" },
      { type: "p", text: "Wires are final. There's no fraud-protection backstop the way there is on a credit card. Once the receiving bank releases the funds, the money is gone. That asymmetry makes wire-controlling systems different from every other login in the business. A breached email account is bad. A breached wire-initiation account is catastrophic, immediately, with no recovery path." },
      { type: "quote", text: "If you're gonna send a wire, there is no recourse once the wire has been sent.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "h2", text: "What 'Nothing Has Happened Yet' Was Actually Doing" },
      { type: "p", text: "The team had been operating this way for years. Nothing had gone wrong. The absence of an incident was being read, implicitly, as a signal the controls were adequate. That is not how risk works." },
      { type: "quote", text: "And to us, it was fascinating that nothing had ever happened. It was a matter of time.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "h2", text: "What We Deployed" },
      { type: "ul", items: ["MFA across the wire-initiation systems and the broader Microsoft 365 environment. Microsoft Authenticator and Duo by Cisco.", "Avanan (a Checkpoint tool) for behavioral email security — catches targeted, lookalike, social-engineered emails that match the shape of legitimate correspondence.", "SentinelOne EDR on every endpoint. If a credential does get away, the endpoint layer watches for the keylogger, the lateral movement, the off-hours data access.", "24/7 SOC monitoring layered on top of the EDR signals, so alerts that matter get human eyes inside minutes."] },
      { type: "h2", text: "What This Means for Any Business Like This One" },
      { type: "ul", items: ["Price the control against the worst case, not the average case. If the worst plausible incident is a six- or seven-figure event, the security stack that prevents it has to be authorized at a number that reflects that.", "MFA is the cheapest, fastest single control you can put in place. If you're running any system that authorizes money movement, vendor changes, or admin access, and it's protected by a username and password alone, that's the first call to make this week.", "'Nothing has happened yet' is a luck balance, not a security posture. The longer the streak, the larger the eventual loss tends to be."] },
    ],
  },
  {
    slug: "optometry-practice-no-mfa-hipaa-exposure",
    title: "HIPAA risk assessment for small practices: what a six-doctor optometry office taught us",
    date: "Feb 13, 2026",
    readTime: "5 min read",
    tag: "Cybersecurity",
    desc: "A six-doctor optometry practice in Plano called because the office manager couldn't manage it anymore. 27 inboxes, patient SSNs moving every day, no MFA, no email security, no SOC.",
    content: [
      { type: "p", text: "A six-doctor optometry practice in Plano called because the office manager couldn't manage it anymore. Twenty-seven inboxes. Patient SSNs and PHI moving every day. No MFA. No email security. No SOC. No EDR. Nobody had been hacked yet, which is exactly why the gaps had survived this long. A real HIPAA risk assessment would have surfaced them before an OCR audit or a breach did." },
      { type: "h2", text: "The 60-Second Version" },
      { type: "ul", items: ["The practice: Six doctors, 27 email users, millions in annual patient revenue. Plano, TX.", "The gap: No MFA. No email security beyond M365 defaults. No 24/7 SOC. No EDR. PHI including patient SSNs on workstations and in email.", "How they found us: The office manager Googled. 'It's just gotten to be too much.'", "What got deployed: Phased rollout: email security, MFA, EDR, 24/7 SOC, SSO to offset the friction doctors hate.", "The point: A HIPAA risk assessment is supposed to find the gaps before the incident does."] },
      { type: "h2", text: "The Call That Started It" },
      { type: "quote", text: "It's just gotten to be too much. I can't manage the day-to-day office and then try to figure out what's going on with email security and the people that are asking questions. I can no longer do it. I need somebody to help me. And I really don't know what I'm asking for because I've never done this before.", author: "Office Manager — paraphrased by Farzad Vahid, Founder and CEO, Fornida" },
      { type: "p", text: "This is the 20-employee tipping point in healthcare. Below it, one person can run IT alongside everything else. Above it, the cracks show, and the office manager feels them long before any incident does." },
      { type: "h2", text: "What We Found Inside" },
      { type: "quote", text: "They have PII data, which is people's personal information. They have social security numbers, they have all this information, and if you're not protecting it... they didn't have multifactor, they didn't have email security, they didn't have a SOC.", author: "Farzad Vahid, Founder and CEO, Fornida" },
      { type: "quote", text: "They do millions of dollars a year with patients... if you get hacked and you leak this PII data, depending on what state you're in, you get fined per user credentials that you lost. So it could be very costly. So much so that you've shut down.", author: "Farzad Vahid" },
      { type: "h2", text: "The Education-Led Conversation, Not the Fear Pitch" },
      { type: "quote", text: "I was like, look, there are gonna be some aspects of your business that will be slowed down from putting in all these cybersecurity measures. However, it'll be offset with some of the things that we do to speed things up. A good example would be like single sign-on so they don't have to go into every single place and do multifactor and all.", author: "Farzad Vahid" },
      { type: "h2", text: "What Got Deployed, and How" },
      { type: "quote", text: "We try to limit the interruptions and maximize the efficiency. You go in and you wanna rip and replace everything. One, it's very costly. And two, it's very difficult because everybody in that environment has to learn an entire new system and process.", author: "Farzad Vahid" },
      { type: "p", text: "Phased, not rip-and-replace. Email security and MFA early; SSO alongside MFA so the friction never hits the doctors unaccompanied; EDR in the background; the 24/7 SOC tuned to the practice's baseline over weeks." },
      { type: "h2", text: "What This Means for Any Small Healthcare Practice" },
      { type: "p", text: "A HIPAA risk assessment is supposed to surface operator-grade gaps, not just generate a checkbox PDF. Per-credential fines apply when records leak. Audit findings apply when controls are missing, breach or no breach. The useful question is not 'have we been hacked?' The useful question is 'if a HIPAA auditor walked in tomorrow, what would they find first?'" },
      { type: "p", text: "Ask any IT vendor: How do you run a HIPAA risk assessment? What technical safeguards do you verify first? Do you stock hardware for next-day replacement? Are there engineers, not technicians, on the help desk? Do you run a 24/7 SOC, or outsource one?" },
    ],
  },
  {
    slug: "tabletop-exercises-incident-response-readiness",
    title: "HIPAA breach notification rule: why most tabletop exercises fail under pressure",
    date: "Feb 6, 2026",
    readTime: "5 min read",
    tag: "Cybersecurity",
    desc: "A multi-facility hospital group with 13,000 employees got breached. The response required 21 consultants billing ~$275/hr for six months. The hospital had a tabletop exercise document. Nobody had practiced it.",
    content: [
      { type: "p", text: "A multi-facility hospital group with 13,000 employees got breached. The response required 21 consultants billing roughly $275 an hour for six months to a year, or $20 to $30 million in consulting alone before hardware or legal. Steven, one of our senior engineers, sat on-site as their interim CISO. The defining failure wasn't a missing tool. They had a tabletop exercise document. Nobody had practiced it." },
      { type: "h2", text: "The 60-Second Version" },
      { type: "ul", items: ["A 13,000-employee hospital group was compromised. Fornida placed a senior engineer on-site as interim CISO.", "The IR effort grew to 21 consultants at ~$275/hr for six months to a year — $20–30M in consulting alone, before hardware or legal.", "The hospital had a written response plan and documented tabletops. They were never rehearsed.", "The chaos wasn't technical. It was role clarity: who calls the carrier, the lawyer, the MSP? Nobody knew.", "A plan on paper isn't readiness. Readiness is rehearsal, especially when breach-notification obligations start immediately."] },
      { type: "h2", text: "What 21 Consultants Actually Buys You" },
      { type: "quote", text: "They had 20 other consultants that came in. So a total of like 21 consultants billing at something like $275 an hour for six months to a year. So they spent $20 to $30 million just on consultants, not talking all the hardware.", author: "Farzad Vahid, CEO, Fornida" },
      { type: "quote", text: "It was a complete mess. A lot of people were pointing fingers, trying to eradicate the threat actors. There's so much PII data that was released because, 13,000 just employees, you can imagine the amount of customers they had.", author: "Farzad Vahid" },
      { type: "h2", text: "The Tabletop That Lived Only on Paper" },
      { type: "quote", text: "All these big hospitals have a response plan. They have a tabletop that they go through exercise. But what we found was a lot of these tabletop exercises just weren't being done. Like, people weren't doing what they were supposed to be doing. And that's why our employee that went there as the CISO was just ripping his hair out.", author: "Farzad Vahid" },
      { type: "p", text: "A tabletop exercise is the named ritual: leadership, IT, legal, comms, and the security partner in a room running a mock incident. Somebody reads a script and the room walks through the next four hours in real time. In healthcare, that rehearsal is where you find out whether the breach-notification chain actually works before the HIPAA clock starts." },
      { type: "quote", text: "When something happens at your network, whose job is it to call the lawyers? Whose job is it to call the cybersecurity insurance company? Whose job is it to call our MSP? If you don't do that exercise, everybody's pointing at each other. Well, I thought that was your job. I thought that was your job.", author: "Farzad Vahid" },
      { type: "h2", text: "What This Means for Any Business, Even a 30-Person One" },
      { type: "ul", items: ["The HIPAA breach notification rule forces role clarity, not just documentation. Naming five accountable owners would have started to fix the hospital. Same at 30 employees: who calls the bank, who calls the lawyer, who calls the MSP — written down and rehearsed.", "A tabletop has to be real to count. Read from a script. Set a clock. Don't pause to check the binder. If somebody can't answer in real time, that's the gap.", "Cyber security incident response services still matter, but they sit downstream of readiness. $20–30M of billed time, and the incident dragged on because the coordination layer wasn't there. Spending more on response is not the same as being ready for it."] },
      { type: "p", text: "The eye-opening part of working a breach at that scale isn't the technical complexity. It's how much of the chaos was avoidable — by an exercise the organization had already paid to write." },
    ],
  },
  {
    slug: "microsoft-365-license-sprawl-offboarding",
    title: "Why Your Microsoft 365 Bill Keeps Growing (and What Your GM Doesn't Know About Your IT Spend)",
    date: "Feb 3, 2026",
    readTime: "7 min read",
    tag: "IT Management",
    desc: "A GM was running IT on the side of his real job. He onboarded every new hire but never canceled licenses for people who left. The Microsoft 365 bill went from $1,500 to $4,000/month before anyone noticed.",
    content: [
      { type: "p", text: "A General Manager at a growing services company was running IT on the side of his real job. He onboarded every new hire — laptop, M365 license, the whole setup. He just never got around to canceling the licenses for the people who left. The Microsoft 365 bill went from about $1,500 a month to about $4,000 a month before anyone noticed. When we audited it, twenty ex-employees still had active seats." },
      { type: "h2", text: "Why This Happens" },
      { type: "p", text: "Onboarding scales naturally. Offboarding doesn't. When a company hires someone, the work is visible. Laptop, email address, license, phone extension. When a company offboards someone, the work is invisible. The person walks out the door. But the M365 license, the Adobe seat, the VoIP extension, the backup user — those don't show up in a meeting. They just continue to bill, automatically, because that's what SaaS does." },
      { type: "quote", text: "$10 a month doesn't seem like a lot, but when you have twenty people that you've offboarded and they're still paying for the Office 365, it's $200 a month. That's just a small example of licensing. If you don't cancel it, it just continues to rack up.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "What It Looks Like in Practice" },
      { type: "p", text: "Twenty inactive M365 seats at roughly $10 each is $200 a month, $2,400 a year. That's the floor. The actual number gets bigger fast, because M365 is rarely the only thing leaking." },
      { type: "p", text: "A few of the other places we routinely find license sprawl when we run an audit:" },
      { type: "ul", items: ["Adobe Creative Cloud. Per-seat pricing assigned to designers and marketing hires who are gone. One forgotten Adobe seat is roughly the cost of eight forgotten M365 seats.", "VoIP and phone extensions. Carriers bill per line, per extension, per number. Nobody removes a line because nobody wants to be the person who deletes the wrong one.", "Backup licenses. Most backup tools bill per protected endpoint. When a laptop goes back into the closet, the backup license quietly continues to back up nothing.", "Niche SaaS. The CRM seat for the salesperson who left. The PM tool seat for the contractor who finished."] },
      { type: "quote", text: "That goes for Microsoft. It goes for anything really. Even your phone lines, it can go for your backups, all of that. You have to manage every single piece of license. Adobe, it could be anything. So if you don't have a protocol for offboarding people and you're not canceling all those licenses, you're basically throwing money away.", author: "Farzad Vahid, Founder, Fornida" },
      { type: "h2", text: "What to Do About It" },
      { type: "h3", text: "1. Run a License Audit" },
      { type: "p", text: "All vendors, all SaaS, all phone lines, all backup software. Pull the current invoice for each one and reconcile against the active employee list. Most owners are surprised by what comes off the list in the first hour — not because the spend is huge, but because the names on the licenses are people who haven't worked there in a year." },
      { type: "h3", text: "2. Build an Offboarding Protocol That Includes License Cancellation" },
      { type: "quote", text: "We like to cancel and just start over. It's just easier to manage 'cause then you're not getting like older emails. You just start over fresh.", author: "Farzad Vahid" },
      { type: "p", text: "Not 'transfer the inbox to a manager,' not 'leave it active just in case.' Cancel the license, archive the data externally if it matters for compliance or knowledge retention, and move on. It's cleaner for the bill, cleaner for the audit trail, and cleaner for security. Abandoned credentials sitting in a forgotten account are the kind of thing that gets phished into a problem later." },
      { type: "h3", text: "3. Hand the Seat-Count Work to Someone Who Watches It" },
      { type: "p", text: "This is where the GM-running-IT pattern has to stop. A General Manager doing IT on the side will keep doing the visible work (onboarding, laptop hand-out, new-hire setup) and keep dropping the invisible work. That's not a personal failing; it's what happens when IT is on the side of someone's desk." },
      { type: "p", text: "The structural answer is co-managed IT. The General Manager keeps the parts that need a person inside the company. A managed IT partner picks up the parts that need someone whose full-time job it is to watch them: license audits, offboarding execution, vendor renewals, the quarterly reconciliation." },
      { type: "h2", text: "What This Isn't" },
      { type: "p", text: "The licensing model isn't predatory. Per-user-per-month is how SaaS economics work, and Microsoft, Adobe, and the VoIP carriers are partners we recommend. The point isn't to switch vendors; it's to manage the seats you're already paying for. And the General Manager isn't doing a bad job. He's doing IT on the side of running the business. That's a structural problem, not a competence problem." },
    ],
  },
];

export function getArticle(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}
